LangString addOrReinstall ${LANG_SIMPCHINESE} "添加/重新安装组件"
LangString alreadyInstalled ${LANG_SIMPCHINESE} "已安装"
LangString alreadyInstalledLong ${LANG_SIMPCHINESE} "${PRODUCTNAME} ${VERSION} 已安装。请选择要执行的操作，然后点击下一步继续。"
LangString appRunning ${LANG_SIMPCHINESE} "{{product_name}} 正在运行，请先关闭后再试。"
LangString appRunningOkKill ${LANG_SIMPCHINESE} "{{product_name}} 正在运行。$\n点击确定将其关闭。"
LangString chooseMaintenanceOption ${LANG_SIMPCHINESE} "请选择要执行的维护操作。"
LangString choowHowToInstall ${LANG_SIMPCHINESE} "请选择 ${PRODUCTNAME} 的安装方式。"
LangString createDesktop ${LANG_SIMPCHINESE} "创建桌面快捷方式"
LangString dontUninstall ${LANG_SIMPCHINESE} "不卸载"
LangString dontUninstallDowngrade ${LANG_SIMPCHINESE} "不卸载（此安装程序不允许直接降级）"
LangString failedToKillApp ${LANG_SIMPCHINESE} "无法关闭 {{product_name}}，请手动关闭后重试。"
LangString installingWebview2 ${LANG_SIMPCHINESE} "正在安装 WebView2…"
LangString newerVersionInstalled ${LANG_SIMPCHINESE} "系统中已安装更高版本的 ${PRODUCTNAME}。不建议安装旧版本；如需继续，建议先卸载当前版本。"
LangString older ${LANG_SIMPCHINESE} "较旧或未知"
LangString olderOrUnknownVersionInstalled ${LANG_SIMPCHINESE} "系统中已安装 $R4 版本的 ${PRODUCTNAME}。建议先卸载当前版本再继续。"
LangString silentDowngrades ${LANG_SIMPCHINESE} "静默安装不支持降级，请改用图形安装界面。$\n"
LangString unableToUninstall ${LANG_SIMPCHINESE} "无法卸载。"
LangString uninstallApp ${LANG_SIMPCHINESE} "卸载 ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_SIMPCHINESE} "安装前先卸载"
LangString unknown ${LANG_SIMPCHINESE} "未知"
LangString webview2AbortError ${LANG_SIMPCHINESE} "WebView2 安装失败，缺少它时应用无法运行。请重新启动安装程序。"
LangString webview2DownloadError ${LANG_SIMPCHINESE} "下载 WebView2 失败：$0"
LangString webview2DownloadSuccess ${LANG_SIMPCHINESE} "WebView2 安装程序下载完成"
LangString webview2Downloading ${LANG_SIMPCHINESE} "正在下载 WebView2 安装程序…"
LangString webview2InstallError ${LANG_SIMPCHINESE} "WebView2 安装失败，退出码：$1"
LangString webview2InstallSuccess ${LANG_SIMPCHINESE} "WebView2 安装成功"
LangString deleteAppData ${LANG_SIMPCHINESE} "清除应用数据和默认表情库（保留飞书组件、自定义表情库）"
